import Link from 'next/link'
import { CheckCircle2, AlertCircle, XCircle, ArrowRight, Shield, Heart, Baby, BookOpen, Server, FileText, Sparkles, AlertTriangle, ChevronDown } from 'lucide-react'

export default function Book1Page() {
  return (
    <>
      <section className="relative pt-24 pb-16 md:pt-32 md:pb-24 bg-gradient-to-br from-[#F5F1E8] to-[#EBE5D5]">
        <div className="max-w-6xl mx-auto px-5 md:px-8">
          <div className="grid gap-12 lg:grid-cols-2 lg:items-center">
            <div>
              <div className="inline-flex items-center gap-2 rounded-full bg-[#1B3B36] px-4 py-1.5 mb-6"><span className="text-xs font-medium text-[#C9A86A]">RAISING A WELL-ROUNDED DOG. BUILDING A STRONGER FAMILY.</span></div>
              <h1 className="font-serif text-4xl md:text-5xl lg:text-6xl font-bold leading-tight mb-4"><span className="text-[#1A2B3D]">BEFORE YOU</span><br /><span className="text-[#722F37]">SAY YES</span><br /><span className="text-[#1A2B3D]">TO THE DOG</span></h1>
              <p className="text-lg text-[#6B5D4F] italic mb-6">The family readiness guide for bringing a puppy home</p>
              <div className="w-16 h-1 bg-[#C9A86A] rounded-full mb-6" />
              <p className="text-lg text-[#2A2520] leading-relaxed mb-8">Most dog books teach you how to <em>train the dog</em>.<br />This one asks a different question:<br /><strong className="text-[#1B3B36]">Is your family actually ready for one?</strong></p>
              <div className="flex flex-col sm:flex-row gap-3"><Link href="/quick-check" className="book-btn-primary">Take the Family Readiness Test™ <ArrowRight className="h-4 w-4" /></Link><Link href="/read-inside" className="book-btn-outline">Read Inside</Link></div>
            </div>
            <div className="flex justify-center lg:justify-end"><div className="relative"><div className="absolute inset-0 bg-[#C9A86A]/20 blur-3xl rounded-full" /><img src="/book-cover-1.png" alt="Before You Say Yes to the Dog book cover" className="relative w-full max-w-sm rounded-lg shadow-2xl" width={426} height={640} /></div></div>
          </div>
        </div>
      </section>
      <section className="py-16 md:py-24 bg-[#F5F1E8]"><div className="max-w-3xl mx-auto px-5 md:px-8 text-center"><h2 className="font-serif text-3xl md:text-4xl font-bold text-[#1B3B36] mb-6">A puppy doesn't enter your dream.<br />He enters your house.</h2><div className="w-16 h-1 bg-[#C9A86A] rounded-full mx-auto mb-8" /><div className="space-y-4 text-lg text-[#2A2520]"><p>Bringing a puppy home is exciting. But the puppy is only one part of the equation.</p><p>There are the early mornings, potty accidents, biting, chewing, barking, cleaning, disrupted sleep, children who want to play constantly, and the everyday responsibility that someone has to carry.</p><p className="font-serif text-xl text-[#1B3B36] italic">And when the excitement fades, the family system is what remains.</p></div></div></section>
      <section className="py-16 md:py-24 bg-[#1B3B36] text-white"><div className="max-w-4xl mx-auto px-5 md:px-8"><h2 className="font-serif text-3xl md:text-4xl font-bold text-center mb-2">A Dog Is a Family Decision</h2><p className="text-center text-[#C9A86A] text-lg italic mb-8">Wanting a dog is easy. Being ready for one is different.</p><div className="w-16 h-1 bg-[#C9A86A] rounded-full mx-auto mb-12" /><div className="grid gap-4 md:grid-cols-2">{['Who actually owns the responsibility?','What will the kids really do?','Who handles the difficult days?','Is the house prepared?','Can Mum have space and control?','How much daily work can the family carry?','What happens when the puppy doesn\'t behave like the dream?','Are you prepared for years of responsibility?'].map((q,i)=>(<div key={i} className="flex items-start gap-3 p-4 rounded-lg bg-white/5 border border-white/10"><AlertTriangle className="h-5 w-5 text-[#C9A86A] shrink-0 mt-0.5" /><span className="text-white/90">{q}</span></div>))}</div><p className="text-center text-xl text-white mt-12 font-serif italic">The book doesn't ask whether your family loves dogs.<br />It asks whether your family can carry one.</p></div></section>
      <section className="py-16 md:py-24 bg-[#F5F1E8]"><div className="max-w-4xl mx-auto px-5 md:px-8"><div className="text-center mb-12"><h2 className="font-serif text-3xl md:text-4xl font-bold text-[#1B3B36] mb-2">The Family Readiness Test™</h2><p className="text-lg text-[#6B5D4F] italic">Before you choose the puppy, test the family.</p><div className="w-16 h-1 bg-[#C9A86A] rounded-full mx-auto mt-6" /></div><div className="grid gap-4 md:grid-cols-3 mb-8">{[{icon:CheckCircle2,label:'PASS',desc:'Proceed carefully.',color:'text-emerald-600 bg-emerald-50'},{icon:AlertCircle,label:'PAUSE',desc:'Fix weak points, then test again.',color:'text-amber-600 bg-amber-50'},{icon:XCircle,label:'NOT READY',desc:'Don\'t bring the puppy home yet.',color:'text-red-600 bg-red-50'}].map((item,i)=>(<div key={i} className="book-card text-center"><div className={`inline-flex h-12 w-12 items-center justify-center rounded-full ${item.color} mb-3`}><item.icon className="h-6 w-6" /></div><h3 className="font-bold text-[#1B3B36] text-lg mb-1">{item.label}</h3><p className="text-sm text-[#6B5D4F]">{item.desc}</p></div>))}</div><div className="text-center"><Link href="/quick-check" className="book-btn-primary">Take the Free Quick Check <ArrowRight className="h-4 w-4" /></Link></div></div></section>
      <section className="py-16 md:py-24 bg-[#EBE5D5]"><div className="max-w-5xl mx-auto px-5 md:px-8"><div className="text-center mb-12"><h2 className="font-serif text-3xl md:text-4xl font-bold text-[#1B3B36] mb-2">What's Inside</h2><p className="text-lg text-[#6B5D4F] italic">Two Parts. One Family System.</p><div className="w-16 h-1 bg-[#C9A86A] rounded-full mx-auto mt-6" /></div><div className="grid gap-8 md:grid-cols-2"><div className="book-card"><div className="inline-flex items-center gap-2 rounded-full bg-[#1B3B36] px-3 py-1 mb-4"><BookOpen className="h-3.5 w-3.5 text-[#C9A86A]" /><span className="text-xs font-semibold text-[#C9A86A]">PART ONE — READ TO KNOW</span></div><ul className="space-y-2 text-sm text-[#2A2520]">{['Is your family really ready?','Who owns the responsibility?','What happens when the excitement disappears?','How should children participate?','How does Mum get space?','How should the house be prepared?','What does the first 48 hours look like?','How do you prevent predictable problems?'].map((item,i)=>(<li key={i} className="flex items-start gap-2"><span className="text-[#C9A86A] mt-0.5">◆</span>{item}</li>))}</ul></div><div className="book-card"><div className="inline-flex items-center gap-2 rounded-full bg-[#722F37] px-3 py-1 mb-4"><Server className="h-3.5 w-3.5 text-white" /><span className="text-xs font-semibold text-white">PART TWO — USE TO DO</span></div><div className="grid grid-cols-2 gap-2 text-sm">{['Family Readiness Test™','First 48 Hours','House Setup','Potty Training','Mum SAFE','Kids Daily Operator','Visitors & Deliveries','Outdoor Freedom','Mental Games','Hygiene','Emergency','Reset'].map((item,i)=>(<div key={i} className="flex items-center gap-1.5"><FileText className="h-3.5 w-3.5 text-[#C9A86A] shrink-0" /><span className="text-xs">{item}</span></div>))}</div></div></div><p className="text-center font-serif text-xl text-[#1B3B36] italic mt-8">Read to know. Use to do.</p></div></section>
      <section className="py-16 md:py-24 bg-[#F5F1E8]"><div className="max-w-4xl mx-auto px-5 md:px-8"><div className="text-center mb-12"><h2 className="font-serif text-3xl md:text-4xl font-bold text-[#1B3B36] mb-2">Everyone Has a Role</h2><div className="w-16 h-1 bg-[#C9A86A] rounded-full mx-auto mt-6" /></div><div className="grid gap-6 md:grid-cols-3"><div className="book-card text-center"><div className="inline-flex h-14 w-14 items-center justify-center rounded-full bg-[#1B3B36]/10 mb-4"><Shield className="h-7 w-7 text-[#1B3B36]" /></div><h3 className="font-serif text-xl font-bold text-[#1B3B36] mb-2">Dad Owns the System</h3><p className="text-sm text-[#6B5D4F]">Safety, freedom, gates, visitors, vet decisions and resets.</p></div><div className="book-card text-center"><div className="inline-flex h-14 w-14 items-center justify-center rounded-full bg-[#C9A86A]/10 mb-4"><Baby className="h-7 w-7 text-[#C9A86A]" /></div><h3 className="font-serif text-xl font-bold text-[#1B3B36] mb-2">Kids Become Operators</h3><p className="text-sm text-[#6B5D4F]">Clear, age-appropriate roles. Playing with the puppy ≠ caring for the puppy.</p></div><div className="book-card text-center"><div className="inline-flex h-14 w-14 items-center justify-center rounded-full bg-[#722F37]/10 mb-4"><Heart className="h-7 w-7 text-[#722F37]" /></div><h3 className="font-serif text-xl font-bold text-[#1B3B36] mb-2">Mum Gets Space</h3><p className="text-sm text-[#6B5D4F]"><strong>Mum gets space. Puppy gets control.</strong></p></div></div></div></section>
      <section className="py-16 md:py-24 bg-gradient-to-br from-[#722F37] to-[#1B3B36] text-white"><div className="max-w-2xl mx-auto px-5 md:px-8 text-center"><h2 className="font-serif text-3xl md:text-4xl font-bold mb-4">Before You Bring the Puppy Home...</h2><div className="w-16 h-1 bg-[#C9A86A] rounded-full mx-auto mb-8" /><p className="text-xl text-white/90 mb-8">Test the family. Build the system. Then make the decision.</p><p className="font-serif text-2xl text-[#C9A86A] italic mb-8">System first. Puppy second. Family always.</p><div className="p-6 rounded-xl bg-white/10 border border-white/20"><p className="text-lg font-semibold mb-2">📖 Coming Soon</p><p className="text-sm text-white/70 mb-4">The book isn't on Amazon yet. Take the free Quick Check now.</p><Link href="/quick-check" className="inline-flex items-center justify-center gap-2 bg-[#C9A86A] text-white font-semibold px-6 py-3 rounded-lg hover:bg-[#DDB87A]">Take the Quick Check <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    </>
  )
}
