// Extracted from Mowebsite's seed-quote-articles.ts, where the array was declared
// inside main(). Hoisted to a module export so the merge script can import it.
export const quoteArticles = [
    {
      slug: 'puppy-enters-your-house-not-your-dream',
      title: 'A Puppy Does Not Enter Your Dream — He Enters Your House',
      excerpt:
        'The moment a puppy crosses your threshold, the fantasy ends and the household system begins. Wanting a dog is not the same as being ready for one.',
      content: `There is a moment every new dog owner remembers with uncomfortable clarity. It is not the moment they decided to get a dog. It is not the moment they picked the puppy up at the breeder or the shelter. It is the moment the puppy actually crossed the threshold of their front door and the fantasy evaporated. What replaced it was not disappointment exactly, but a sudden, overwhelming awareness that a living, breathing, unpredictable creature was now inside their house and nothing — not the Instagram posts, not the YouTube videos, not the warm feelings they had been carrying for months — had prepared them for what that actually meant.

I wrote this idea plainly in Before You Say Yes to the Dog: a puppy does not enter your dream. He enters your house. And the house must be ready. That distinction between dream and house is not rhetorical. It is the entire difference between families who succeed with dogs and families who do not. The dream lives in your imagination. It is peaceful, obedient, and perfectly timed. The puppy lives in your hallway, on your carpet, at three in the morning, and he does not care about your imagination. He cares about his bladder, his teeth, his energy, and his curiosity. He will chew the thing you love most. He will pee on the surface you cleaned most recently. He will bark at the hour you need silence most desperately. None of this is malice. It is simply what puppies do when they are placed inside a house that was designed for humans, not for them.

The problem is not that people dream. The problem is that people mistake the dream for preparation. They spend weeks or months picturing what it will be like to have a dog. They imagine walks in the park, cosy evenings on the sofa, a loyal companion for the children. These images are not wrong — they are just incomplete. They represent perhaps twenty percent of the actual experience. The other eighty percent is logistics, management, cleaning, scheduling, coordinating, and problem-solving. It is the work that nobody photographs and nobody posts about. It is the work that makes the dream possible, and it is the work that most families are not prepared for when the puppy arrives.

Readiness is not about enthusiasm. Enthusiasm is abundant on day one. Readiness is about infrastructure. Do you have a plan for where the puppy sleeps? Not a vague idea — an actual plan, tested and agreed upon by every adult in the house. Do you have a potty schedule? Do you know who will be home at 2pm on a Tuesday in three weeks when the puppy needs to go out? Do you have gates, a crate, cleaning supplies, and a clear agreement about which rooms the puppy can access? These are not exciting questions. They are the questions that determine whether the puppy's first week feels like a joy or a crisis.

The reason this matters so much is that the first two weeks are decisive. This is the window during which the household either adapts to the puppy or begins to fracture under the pressure. If the system is in place before the puppy arrives, the first two weeks are challenging but manageable. The family knows who does what, when, and why. If the system is not in place, the first two weeks become a blur of exhaustion, resentment, and emergency decisions made at 4am. By the end of that period, the dream is not just evaporated — it is replaced by something much harder to recover from: the belief that getting the dog was a mistake.

So the question is not whether you want a puppy. Almost everyone who asks that question already knows the answer. The question is whether your house is ready. Not kind of ready. Not almost ready. Ready. That means the family has discussed and agreed on the core questions. It means the physical environment has been adjusted. It means the daily schedule has been mapped out and the responsibilities have been distributed with honesty, not optimism. It means the least enthusiastic person in the family has been heard and their concerns have been addressed, not dismissed.

A puppy will enter your house whether it is ready or not. That is not negotiable. What is negotiable — what is entirely within your control — is the condition of the house when he does. The dream was the inspiration. The house is the reality. And the reality is where the dog will live, sleep, eat, and grow. Make it ready, and the dream has a chance of becoming real. Leave it unready, and the dream will remain exactly that — a dream that cost you money, time, and a puppy's chance at a stable home.`,
      topic: 'Dog Ownership',
      published: false,
      featured: false,
    },
    {
      slug: 'love-is-not-the-system',
      title: 'Love Is Not the System: Why Good Intentions Will Not Raise Your Dog',
      excerpt:
        'Love matters deeply, but love cannot wake at 3am for potty breaks or manage gates. The system carries the workload — love makes it worth building.',
      content: `Nobody doubts that you love your dog. The question is whether love is enough to raise him well. And the honest answer, the one that most dog owners discover in the first few weeks of ownership, is that it is not. Love is necessary but profoundly insufficient. It is the motivation, not the mechanism. It is the reason you build the system, not the system itself. And confusing the two — believing that because you love your dog, everything will somehow work out — is one of the most common and most damaging mistakes new owners make.

Consider what love actually does in the context of dog ownership. Love makes you want the dog. Love makes you forgive the chewed shoes and the accidents on the rug. Love makes you sit on the kitchen floor at midnight because the puppy is crying in his crate and you cannot bear to let him suffer. These are real and valuable things. But love does not wake you up at 3am when the puppy needs to go out and nobody set an alarm. Love does not remember that the puppy has been in his crate for four hours because everyone lost track of time. Love does not manage the gate between the kitchen and the living room, or notice that the children have been leaving their snacks on the floor where the puppy can reach them, or coordinate who is picking up the dog food on the way home from work.

These are system tasks. They are logistical, practical, and time-sensitive. They require planning, communication, and follow-through. They require someone — ideally multiple someones — to think ahead, to notice patterns, to adjust routines when circumstances change. Love does none of this automatically. Love assumes that someone will handle it. And when no one does, the system breaks down, and the puppy suffers not from a lack of love but from a lack of management.

This is why I distinguish so sharply between love and system. Not because love does not matter — it matters enormously — but because families lean on love as a substitute for planning and then are genuinely confused when things go wrong. They say things like "but we love him so much" as though that should be sufficient explanation for why the dog is not house-trained, or why the children are scared of him, or why the house is in a constant state of chaos. Love is the emotional foundation. The system is the operational structure. You need both. But you only have to build one of them, and it is not love.

The system is the set of agreements, routines, rules, and physical arrangements that govern how the dog lives in your house. It includes feeding schedules, potty routines, exercise plans, sleeping arrangements, gate placements, visitor protocols, and the division of responsibilities among family members. It is the infrastructure that makes daily life with a dog possible without constant crisis. And like any infrastructure, it must be designed before it is needed, not improvised while things are already falling apart.

Building the system does not diminish love. In fact, it honours it. When you take the time to plan your puppy's daily routine, you are saying: this dog matters enough for me to think carefully about his life. When you set up gates and establish rules about which rooms are accessible, you are saying: this dog deserves a safe, predictable environment. When you distribute responsibilities fairly and honestly among family members, you are saying: we are in this together, and no single person will carry the burden alone. These are acts of love expressed through action. They are love made operational.

So do not stop loving your dog. Love him fiercely and without apology. But do not confuse that love with readiness. Do not assume that your good intentions will somehow organise themselves into a workable routine. They will not. Build the system deliberately, communicate it clearly, and maintain it consistently. The system is what carries the workload. Love is what makes the workload worth carrying. Both are essential. Only one requires your active, deliberate effort.`,
      topic: 'Dog Ownership',
      published: false,
      featured: false,
    },
    {
      slug: 'dreams-do-not-clean-accidents',
      title: 'Dreams Do Not Clean Accidents: The Hidden Work Behind Dog Ownership',
      excerpt:
        'An honest look at the invisible labour of dog ownership — the cleaning, scheduling, and managing that the romantic image leaves out entirely.',
      content: `When people talk about getting a dog, they describe it in terms of companionship, loyalty, joy, and love. These are real things that dogs provide, and they are the reasons most people want one. But there is another dimension to dog ownership that receives almost no attention in the popular imagination, and it is the dimension that will determine whether the experience succeeds or fails. It is the dimension of work. Not the fun kind of work — the training sessions, the walks in the park, the games of fetch. The other kind. The invisible, repetitive, unglamorous labour that keeps a dog-owning household functioning day after day.

Dreams do not clean accidents. That line is not meant to be cynical. It is meant to be precise. The dream of dog ownership — the image you carry in your mind of what life will be like with a dog — does not include the reality of cleaning urine off a rug at 6am before you have had coffee. It does not include wiping mud off the floor after every walk, or picking up faeces from the garden in the rain, or laundering the dog bed for the third time in a week because the puppy has had digestive issues. These tasks are not dramatic. They are not photographable. They do not make good stories. But they are daily, they are non-negotiable, and they are the reason so many families find themselves overwhelmed within the first month.

The problem is not the work itself. The problem is that families do not see the work coming. They plan for the puppy. They do not plan for the management of the puppy. They think about what breed to get, what name to choose, what collar to buy. They do not think about who will be responsible for the 7am potty break on weekdays, or what happens when the puppy needs to go out during the school run, or how the family will handle the three-week period during which the puppy cannot be left alone for more than an hour. These are logistical questions, and they are unglamorous, and they are the questions that matter most.

The invisible labour of dog ownership falls into several broad categories. First, there is cleaning. Dogs are messy. Puppies are extremely messy. They pee, they poop, they vomit, they shed, they track mud, they chew things into fragments that then need to be swept up. This cleaning is not occasional — it is daily, sometimes hourly. Second, there is scheduling. A puppy's day is structured around biological needs that do not respect your calendar. He needs to eat at regular intervals, go outside at regular intervals, sleep at regular intervals, and have stimulation at regular intervals. Managing this schedule across multiple family members with different commitments is a genuine coordination challenge. Third, there is managing. This means managing the physical environment — gates, closed doors, cleared surfaces, inaccessible bins — and managing the people in the environment — children who leave food around, visitors who do not know the rules, family members who undermine the training by being inconsistent.

None of these tasks requires special expertise. They require attention, consistency, and a willingness to do them even when you are tired, busy, or simply not in the mood. They require the family to treat dog ownership as a shared operational responsibility, not as a hobby that someone does in their spare time. And they require an honest conversation before the puppy arrives about who will do what, when, and how the family will handle the periods when the designated person cannot fulfil their role.

The romantic image of dog ownership is not wrong. It is just radically incomplete. It shows you the destination without the journey. It shows you the dog sleeping peacefully on the sofa without showing you the three months of crate training that made that peace possible. It shows you the children playing happily with the dog in the garden without showing you the supervision, the rules, and the management that keep those interactions safe and positive.

If you are considering a dog, ask yourself not whether you are willing to love one — that answer is almost certainly yes — but whether you are willing to manage one. Whether you are willing to clean up after one, schedule around one, and coordinate with your family about one, every single day, for years. The love is the easy part. The work is the part that determines whether the dog stays.`,
      topic: 'Dog Ownership',
      published: false,
      featured: false,
    },
    {
      slug: 'least-ready-person-real-say',
      title: 'The Least-Ready Person Gets a Real Say: Why the Reluctant Family Member Matters Most',
      excerpt:
        'The person least enthusiastic about getting a dog is the most important person to listen to. If they are not comfortable, failure is only a matter of time.',
      content: `In almost every family that decides to get a dog, there is an imbalance of enthusiasm. One or two people — often the children, sometimes a parent — are absolutely certain. They have been asking for months or years. They have done the research, watched the videos, made the case. And then there is at least one person who is not sure. They have not said no, but they have not said yes either. They have concerns. They worry about the mess, the noise, the responsibility, the cost, the impact on their daily life. They are the least-ready person in the family, and in the standard dynamics of household decision-making, they are also the person most likely to be overruled.

This is a mistake. In fact, it may be the single most consequential mistake a family can make when deciding to get a dog. Because the least-ready person is not an obstacle to be overcome. They are a critical data point. Their reluctance is not negativity or lack of caring — it is an instinctive assessment that the family system is not yet prepared to absorb the impact of a living, dependent animal. And if that person is overruled, if their concerns are dismissed or voted down, what happens next is almost entirely predictable. The puppy arrives. The enthusiastic people are thrilled for approximately ten days. Then reality sets in. The work begins to accumulate. The least-ready person, who was never genuinely on board, starts to feel resentful. The cracks appear, and they widen quickly.

Why does this person matter so much? Because the family system is only as strong as its weakest point of agreement. A dog affects everyone in the household — not just the people who wanted him. He affects the person who did not want him most of all, because that person did not choose this disruption and has not psychologically prepared for it. They did not build the anticipation that sustains people through the hard early weeks. They do not have the emotional buffer of having wanted this. When the puppy wakes them up, when he chews something of theirs, when they have to change their plans to accommodate his needs, they experience these disruptions as impositions, not as shared sacrifices.

The conventional approach is to try to convince this person. To show them cute videos, to make promises about how the children will help, to assure them that it will not be as much work as they think. This approach almost always fails, not because the promises are intentionally dishonest, but because they are made by people who are operating from enthusiasm, not from experience. The person making the promises has not yet lived with a puppy. They do not yet know what they are committing to. Their reassurances are genuine but uninformed, and the least-ready person senses this even if they cannot articulate it.

What works instead is listening. Not polite listening while you wait for your turn to argue — genuine listening. Asking the reluctant person what specifically concerns them, and taking those concerns seriously enough to address them structurally before the puppy arrives. If Mum is worried about the mess, the family needs a concrete plan for who cleans what and when. If Dad is worried about the early mornings, the family needs a schedule that does not default to him. If a teenager is worried about the dog disrupting their study time, the family needs to discuss how the dog will be managed during those hours. These are not problems to be dismissed. They are design constraints that must be resolved before the system can function.

The least-ready person gets a real say not because they have veto power — although in practice, they often should — but because their concerns, when taken seriously and addressed properly, actually make the system stronger. A family that has genuinely discussed and resolved the concerns of its most reluctant member is a family that has done the hard thinking upfront. They have identified the weak points in their plan and reinforced them. They have turned scepticism into structural preparation.

So if someone in your family is not ready, do not push past them. Pull them in. Ask them what would need to change for them to feel comfortable. Then make those changes — not verbally, but structurally — before the puppy arrives. If you cannot make those changes, if the concerns cannot be resolved, that is not a failure of enthusiasm. That is valuable information. It means the system is not ready. And bringing a dog into a system that is not ready is not fair to the dog, and it is not fair to the person who tried to tell you.`,
      topic: 'Family Dogs',
      published: false,
      featured: false,
    },
    {
      slug: 'success-is-not-tricks-calm-predictable-dog',
      title: 'Success Is Not Tricks: What a Well-Raised Dog Actually Looks Like',
      excerpt:
        'Forget impressive tricks and perfect obedience. A successful dog is calm, predictable, and safe to live with. That is the real goal — and it is harder than it looks.',
      content: `When most people imagine a well-trained dog, they picture something specific. A dog who sits on command, shakes hands, rolls over, walks perfectly on a lead without pulling, and perhaps catches a frisbee with athletic grace. These are the images that dominate social media, dog training content, and the public imagination. They are impressive to watch. They are satisfying to demonstrate. And they have almost nothing to do with what actually matters in a family dog.

The popular definition of dog success is performative. It is about what the dog can do on cue, in front of an audience, in controlled conditions. It is a definition that serves the owner's ego more than the dog's wellbeing, and it is a definition that misleads families into pursuing the wrong goals from the very beginning. A dog who can perform twelve tricks but who cannot settle calmly in the living room, who charges the front door when visitors arrive, who resource-guards food, or who cannot be trusted around children without constant supervision is not a well-trained dog. He is a dog with party tricks and behavioural problems.

Before You Say Yes to the Dog challenges this directly. Success is not tricks. A calm, predictable dog the family can safely live with — that is the real goal. This redefinition is not about lowering standards. It is about getting the standards right. Calm means the dog can regulate his own energy. He does not need to be sedated or inactive — he needs to be appropriate. He can be excited when excitement is appropriate and settled when settlement is appropriate. Predictable means the family knows what to expect from him in most situations. They know how he will react to visitors, to loud noises, to food being prepared, to children running through the house. They do not have to hold their breath every time a new situation arises, wondering whether the dog will cope or escalate.

Safely is the critical word. A dog the family can live with safely is a dog who does not pose a risk to children, to visitors, to other animals, or to himself. This does not mean he must be perfectly behaved in every conceivable scenario. It means that in the normal course of daily family life — meals, bedtimes, visitors, play, quiet time — the dog's behaviour is manageable and the family does not feel anxious about what might happen next. Safety is not the absence of all risk. It is the presence of enough predictability that the family can relax.

Why is this so much harder than teaching tricks? Because tricks are discrete, bounded behaviours. You teach sit. You teach paw. You teach down. Each one is a separate unit that can be practised and perfected in short sessions. Calmness and predictability, by contrast, are not discrete behaviours. They are states of being that emerge from consistent daily management over a long period. They are the cumulative result of routines, boundaries, appropriate exercise, clear communication, and a household environment that supports rather than undermines the dog's ability to regulate himself.

A calm, predictable dog is not born. He is made — slowly, deliberately, and through the consistent application of a well-thought-out system. He is the product of a family that understood from the beginning that the goal was not a performing animal but a living companion who could share their home without turning it into a source of constant stress. If you are working towards that goal, you are doing the real work of dog ownership. Everything else is supplementary.`,
      topic: 'Dog Behaviour',
      published: false,
      featured: false,
    },
    {
      slug: 'system-first-puppy-second',
      title: 'System First, Puppy Second: Why the Order Matters More Than You Think',
      excerpt:
        'Building the family system before the puppy arrives is the single most important decision. Waiting is not failure — it is prevention.',
      content: `There is a natural sequence in dog ownership that most families get backwards. They choose the puppy first and build the system afterwards. They fall in love with a breed, find a breeder, pick up the puppy, bring him home, and then — surrounded by chaos, exhaustion, and a small creature who needs immediate, round-the-clock management — they try to figure out how to organise their life around him. This is backwards. It is the equivalent of building an aeroplane while flying it. It sometimes works, but it is stressful, inefficient, and far more likely to end badly.

The correct sequence is system first, puppy second. Build the household infrastructure — the agreements, the routines, the physical arrangements, the division of labour — before the puppy arrives. Not because you are being overly cautious, but because the system is the thing that determines whether the puppy thrives or struggles. The puppy is a variable you cannot fully control. The system is entirely within your control. It makes sense to stabilise what you can before introducing what you cannot.

What does the system actually look like? It looks like a family meeting in which everyone — including the least enthusiastic member — agrees on the basic questions. Where will the puppy sleep? Who will feed him and when? Who will take him out first thing in the morning? What happens during the school day when everyone is out? Which rooms are off-limits? How will visitors be managed? What are the rules about feeding from the table, getting on furniture, and sleeping in bedrooms? These questions do not answer themselves. They require discussion, negotiation, and — critically — genuine agreement. Not reluctant agreement, not passive agreement, not "we will figure it out later" agreement. Genuine, committed, written-down-if-necessary agreement.

The physical environment is part of the system too. Before the puppy arrives, the house should be adjusted. Gates should be in place. Hazardous items should be removed or secured. A sleeping area should be prepared. Cleaning supplies should be readily accessible. Food and water bowls should be positioned. A potty area — whether indoors or out — should be identified and prepared. These physical preparations are not optional extras. They are the visible expression of the invisible agreements the family has made. When the gates are up before the puppy arrives, it means the family has already decided which areas are accessible and which are not. When the sleeping area is prepared, it means the family has already agreed on where the puppy will sleep. These preparations encode decisions into the environment so that when the puppy arrives, the household is already operating according to a plan rather than reacting to emergencies.

Waiting to build the system until after the puppy arrives is common because it feels inefficient. Families think they are saving time by getting the puppy sooner and figuring things out as they go. But the opposite is true. Every day without a system is a day of reactive, ad hoc decision-making that consumes far more energy and creates far more conflict than proactive planning would have required. The family that spends two weeks building a system before the puppy arrives will spend the first two weeks of ownership in a structured, manageable routine. The family that does not will spend those same two weeks in a state of escalating chaos, making decisions under pressure that they will later regret.

Waiting is not failure. It is not hesitation, or lack of commitment, or overthinking. It is prevention. It is the recognition that bringing a living creature into your home is a significant event that deserves preparation, not improvisation. If you are not ready, the most responsible thing you can do is not get the dog yet. Build the system. Test it. Make sure every person in the household understands and agrees to their role. Then, when the system is solid, bring the puppy home. He will not know the difference, but you will. And that difference will shape the entire experience of living together.`,
      topic: 'Puppy Care',
      published: false,
      featured: false,
    },
    {
      slug: 'reliability-before-freedom',
      title: 'Reliability Before Freedom: The Rule That Changes Everything',
      excerpt:
        'Freedom is not a reward for cuteness. It is earned through repeated, consistent good behaviour. One good day is not reliability.',
      content: `There is a powerful temptation in dog ownership to give freedom too early. The puppy has had a good day — no accidents, no chewing, no excessive barking — and the owner decides he has earned the run of the house. Or the puppy looks so happy in the garden that the owner leaves him outside unsupervised for longer than planned. Or the children beg to let the dog sleep on their bed and the parent, tired and wanting peace, says yes just this once. Each of these decisions feels reasonable in the moment. Each of them is likely to cause problems later. The reason is simple: one good day is not reliability.

Reliability means the dog consistently demonstrates the desired behaviour across multiple contexts, over a sustained period, with different people, and in the presence of different distractions. It is not a single event. It is a pattern. A puppy who did not have an accident today has not demonstrated reliability. He has demonstrated one instance of appropriate behaviour, which may have been the result of luck, timing, or the fact that someone took him outside at exactly the right moment. A puppy who has not had an accident for two weeks, across different rooms, different times of day, and different handlers, has begun to demonstrate reliability. That is the threshold at which increased freedom becomes appropriate.

This principle — reliability before freedom — applies to every area of the dog's life. Off-lead freedom at the park comes after the dog has demonstrated reliable recall in low-distraction environments, then medium-distraction environments, and finally high-distraction environments. Access to the living room comes after the dog has demonstrated he can be trusted not to chew the furniture, not to steal food, and not to toilet on the carpet. Sleeping outside the crate comes after the dog has demonstrated he can settle calmly and quietly through the night without needing to be let out or comforted. Each increase in freedom is earned, not given, and the earning happens through repeated, consistent demonstration.

Why does the order matter so much? Because freedom given too early creates opportunities for the dog to practise unwanted behaviours. A puppy who is given the run of the house before he is house-trained will have accidents in rooms the family has not yet managed. Those accidents create habits — for the puppy and for the family. The puppy learns that those rooms are acceptable toilet areas. The family learns to expect mess in those rooms and begins to accept lower standards. The habits compound. The standard slips. And the family finds itself living with a dog who has more freedom than he can handle and less training than he needs.

The reverse is also true. Freedom given at the right time reinforces the dog's good behaviour. When the dog earns access to a new room and handles it well, the family's trust in him grows, and the dog's understanding of what is expected of him deepens. Each successful expansion of freedom is a building block. The dog learns that good things come from good behaviour, and the family learns that the system they have built actually works. This creates a positive feedback loop: reliable behaviour leads to more freedom, which leads to more opportunities to demonstrate reliable behaviour, which leads to more trust and more freedom.

The practical implication is patience. Families must resist the urge to accelerate the timeline. The puppy's progress should dictate the pace, not the family's desire for a fully integrated dog. If the puppy needs three weeks in the kitchen before he can be trusted in the hallway, then three weeks it is. If he needs two months of on-lead walks before his recall is reliable enough for off-lead time, then two months it is. These timelines are not delays. They are the process. Rushing them does not speed anything up. It just creates problems that will take even longer to fix.

Reliability before freedom is not restrictive. It is protective. It protects the dog from situations he is not ready for, and it protects the family's investment in the training they have already done. Give freedom when it is earned, not when it is wanted, and the result will be a dog who is genuinely trustworthy — not a dog who has simply not yet been tested.`,
      topic: 'Dog Behaviour',
      published: false,
      featured: false,
    },
    {
      slug: 'surrender-is-not-shame-reset',
      title: 'Surrender Is Not Shame: Why Resetting Your Dog System Is Not Failure',
      excerpt:
        'If the puppy is home and things are going badly, it is not too late. A reset changes the system, not how hard you try. The trigger is a bad week, not a bad day.',
      content: `There is a particular kind of silence that falls over families who are struggling with their new dog. It is not the silence of peace. It is the silence of people who do not want to say out loud what they are all thinking. The dog is not working out. He is too much. The house is a mess. The children are frightened or resentful. The couple is arguing about whose responsibility it is. And nobody wants to be the one who says the thing that feels like admitting defeat: maybe we made a mistake. That silence is dangerous, because it prevents the family from taking the one action that could save the situation. A reset.

A reset is not a restart. You do not send the dog back and begin again. A reset is a deliberate, structured reassessment of the family system while the dog remains in the home. It is an acknowledgment that the current approach is not working and a commitment to designing a new one. It requires the family to stop what they are doing, step back, and honestly evaluate what has gone wrong and why. It is uncomfortable. It requires honesty, humility, and the willingness to admit that the plan — or the absence of a plan — has failed. But it is not failure itself. It is the opposite of failure. It is the decision to fix things rather than to let them continue to deteriorate.

Surrender is not shame. That phrase is deliberately chosen because the word surrender carries such weight in dog ownership. It evokes the image of a family giving up, returning the dog to the shelter, admitting that they could not handle it. But surrender in the context of a reset means something entirely different. It means surrendering the idea that the current approach will eventually work if you just try harder. It means surrendering the belief that things will improve on their own. It means surrendering the pride that prevents you from admitting you need help. These are not admissions of weakness. They are acts of clarity.

When should a family reset? The trigger is a bad week, not a bad day. Everyone has bad days. The puppy has an accident, the toddler pulls his tail, someone yells, emotions run high. This is normal. It is not pleasant, but it is within the range of normal. A bad week is different. A bad week is a sustained pattern of problems that does not resolve despite the family's best efforts. Accidents that continue despite a potty schedule. Behaviour that gets worse instead of better. Family tension that escalates instead of easing. Sleep deprivation that affects everyone's ability to function. A single bad day is a data point. A bad week is a signal.

The reset process itself has three phases. First, diagnosis. The family identifies what is specifically not working. Not "everything" — that is too vague to be useful. Is the potty training failing because the schedule is unrealistic? Is the dog destructive because he does not have enough appropriate outlets for chewing? Are the children scared because they have not been taught how to interact with the dog safely? Are the adults arguing because the division of labour is unfair? The more specific the diagnosis, the more effective the reset will be.

Second, redesign. The family creates a new system that addresses the specific problems identified in the diagnosis. This may mean tightening the schedule, restricting the dog's access to fewer rooms, increasing exercise, adjusting the feeding routine, or redistributing responsibilities among family members. The key is that the new system is built around the problems, not around optimism. It is designed to work, not to feel good. If the old system was too loose, the new system should be tighter. If the old system relied too heavily on one person, the new system should distribute the load more broadly.

Third, commitment. The family agrees — genuinely, explicitly, and with consequences — to follow the new system for a defined period. Not forever. A period. Two weeks, three weeks, long enough to see whether the changes are producing results. If they are, the family continues. If they are not, the family resets again, because the willingness to reset is itself part of the system. A family that can reset without shame is a family that can solve problems. A family that cannot reset is a family that will eventually surrender in the other sense — the sense they were afraid of all along.`,
      topic: 'Dog Behaviour',
      published: false,
      featured: false,
    },
    {
      slug: 'kids-are-not-guests-dog-system',
      title: 'Kids Are Not Guests: Why Children Must Be Part of the Dog System',
      excerpt:
        'Children cannot be visitors in a dog-owning home. They need real roles and routines — but they also cannot be the promised solution to the workload.',
      content: `When families decide to get a dog, one of the most common refrains is that the children will help. They will feed the dog, walk the dog, clean up after the dog. The dog will teach them responsibility. It will be good for them. This is not wrong in principle. Children can and should participate in the care of a family dog. But the way this participation is usually imagined and communicated is deeply flawed, and it sets up both the children and the dog for failure.

The first problem is the assumption that children will help as though helping were their natural, default state. It is not. Children are not small adults who happen to be shorter. They are developing people with limited attention spans, fluctuating motivation, school pressures, social lives, and — critically — no understanding of what daily dog ownership actually entails. A ten-year-old who enthusiastically promises to walk the dog every morning does not yet know what it means to walk the dog every morning in January, in the rain, before school, when they are tired and would rather stay in bed. Their promise is genuine. Their capacity to fulfil it consistently is not.

The second problem is the use of children as the justification for getting the dog. When a parent says "the kids will take care of it," they are not making a practical plan. They are making a rationalisation. They are finding a way to say yes to something they want while shifting the responsibility onto people who cannot actually carry it. The dog is an adult's decision. The system must be designed by adults and primarily maintained by adults. Children participate within that system, but they do not run it. If the system only works when the children are fully compliant and enthusiastic every day, it is not a system. It is a hope, and hopes break.

This does not mean children have no role. It means their role must be defined clearly, age-appropriately, and realistically. A young child can be responsible for refilling the water bowl. An older child can assist with feeding. A teenager can take the dog for a walk — sometimes. These are genuine contributions, and they matter. But they are contributions within a system that does not depend on them. If the child forgets to refill the water bowl, an adult notices and does it. If the teenager cannot walk the dog because of an exam, an adult takes over. The system absorbs the gaps. The system does not break because a child had a busy week.

Kids are not guests in this system. They are daily operators. The distinction matters. A guest is someone who visits, enjoys the dog, and leaves without contributing to the management. A daily operator is someone who lives in the system, understands the rules, and has specific responsibilities within it. Children should be daily operators. They should know the dog's schedule. They should understand why certain rules exist. They should be able to tell a visitor, "please do not feed the dog from the table, that is our rule." They should feel ownership of the system, not just of the dog.

But — and this is the crucial balance — they cannot be the system's backbone. Adults are the backbone. Adults design the system, maintain the system, and absorb the failures of the system. Children participate, learn, and grow within it. This is not merely practical wisdom. It is fairness to the children, who should not bear the weight of a commitment they did not make, and fairness to the dog, who should not suffer because the people who made the commitment delegated it to people who could not carry it.

If you are building a family dog system, design the children's roles with the same rigour you apply to everything else. Be specific about what they will do, when they will do it, and what happens when they cannot. Make the system robust enough to function even when the children are not contributing. Then let the children's participation be a genuine, valued part of the whole — not the justification for it, and not the assumption it rests upon.`,
      topic: 'Family Dogs',
      published: false,
      featured: false,
    },
    {
      slug: 'goal-is-to-keep-the-puppy',
      title: 'The Goal Is Not to Get the Puppy — The Goal Is to Keep Him',
      excerpt:
        'The most important reframe in dog ownership: the objective is not acquiring a puppy. It is building a household that can keep the dog and live well together.',
      content: `Every year, thousands of families successfully acquire a puppy. They research breeds, visit breeders or shelters, pay money, bring the puppy home, and take photographs. The acquisition is complete. The puppy is theirs. And then, over the following weeks and months, a significant number of those families discover that getting the puppy was the easy part. Keeping the puppy — keeping him healthy, keeping him well-behaved, keeping him in the home as a valued and manageable member of the family — is where the real challenge lies. And it is a challenge that many families were not prepared for, because they never distinguished between the two goals.

The goal is not just to bring the puppy home. The goal is to keep him. This distinction, which sits at the heart of Before You Say Yes to the Dog, is the most important reframe in dog ownership. It changes everything — how you prepare, how you make decisions, how you measure success, and how you respond when things go wrong. When the goal is acquisition, the focus is on choosing the right puppy, finding a good breeder, and getting through the first exciting days. When the goal is retention, the focus shifts to building a household system that can sustain a dog over years of daily life. These are fundamentally different undertakings, and they require fundamentally different preparations.

Consider what it means to keep a dog. It means that six months after the puppy arrives, the family is not exhausted, resentful, or regretful. It means that one year later, the dog is house-trained, reasonably calm, and integrated into the family's daily routines without constant crisis. It means that two years later, the dog is a stable, predictable presence in the household — not a source of stress, not a problem to be managed, but a genuine companion who adds to the family's quality of life. This is the real goal. Everything else — the breed choice, the name, the collar, the first walk — is preamble.

The reason families lose sight of this goal is that the acquisition phase is exciting and the retention phase is not. Choosing a puppy is fun. Building a household system is work. Picking up the puppy is an event. Maintaining a daily routine for months is a discipline. The human brain is wired to pursue the exciting, immediate reward and to underestimate the long-term commitment. This is not a character flaw. It is a cognitive bias. And the way to overcome it is not willpower — it is reframing. By explicitly stating that the goal is to keep the dog, not just to get him, you shift the focus of your preparation from the acquisition moment to the ongoing reality.

This reframe has practical consequences. If the goal is to keep the dog, then the family's preparation must address the long-term questions, not just the short-term ones. It is not enough to ask "which breed is right for us?" You must also ask "who will care for this dog when the initial excitement fades?" It is not enough to prepare the house for the puppy's arrival. You must prepare the family's schedule for the puppy's ongoing needs. It is not enough to agree that everyone wants a dog. You must agree on how the family will handle the disagreements, the setbacks, and the inevitable moments when someone wants to quit.

The families that keep their dogs are not the families that love them most. They are the families that prepared most thoroughly. They are the families who understood, before the puppy arrived, that the first day was not the finish line — it was the starting line. They built a system. They agreed on rules. They distributed responsibilities honestly. They planned for the hard parts, not just the happy parts. And when the hard parts arrived — as they always do — they had the infrastructure in place to absorb the impact without breaking.

If you are reading this before you have a dog, let this be the question that guides your preparation: not "how do I get the right puppy?" but "how do I build a household that can keep a dog?" The answer to that question is the difference between a family that has a dog and a family that keeps one. It is the most important question in dog ownership, and it deserves the most honest, rigorous answer you can give it.`,
      topic: 'Dog Ownership',
      published: false,
      featured: false,
    },
];
